spring:
  datasource:
#    specify at least 2 endpoints
    url: jdbc:yugabytedb://127.0.0.2:5433,127.0.0.3:5433/yugabyte?load-balance=true&yb-servers-refresh-interval=120
    driver-class-name: com.yugabyte.Driver
    username: yugabyte

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.yugabyte.Driver: TRACE
