spring:
  application:
    name: yb-boot-data
  flyway:
    default-schema: stodo
    schemas: stodo,public
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        default_schema: stodo
        hbm2ddl:
          extra_physical_table_types: "PARTITIONED TABLE"
          auto: validate
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
      auto-commit: false
      keepalive-time: 120000
      connection-init-sql: "set yb_silence_advisory_locks_not_supported_error=on; set search_path=stodo,public; begin; prepare warmup as SELECT 1; execute warmup; commit;"
      connection-timeout: 5000
      data-source-properties:
        ApplicationName: yb-ms-data
        socketTimeout: 30
server:
  port: 8080
