micronaut:
  application:
    name: yb-micronaut-data
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:META-INF/resources
  server:
    port: 8090
datasources:
  default:
    auto-commit: false
    data-source-properties:
      currentSchema: mtodo
    minimum-idle: 2
    maximum-pool-size: 10
    keepalive-time: 120000
    connection-init-sql: "set yb_silence_advisory_locks_not_supported_error=on; set search_path=mtodo,public; begin; prepare warmup as SELECT 1; execute warmup; commit;"
flyway:
  datasources:
    default:
      default-schema: mtodo
      schemas: mtodo,public
